In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sp500 = yf.download('^GSPC', start='2018-01-01', end='2022-12-31', progress=False)

YF.download() has changed argument auto_adjust default to True


In [3]:
prices = sp500['Close']

In [4]:
scaled_prices = []

for i in range(len(prices)):
    x = prices.squeeze().iloc[i]
    y = (x - prices.squeeze().min()) / (prices.squeeze().max() - prices.squeeze().min())
    scaled_prices.append(y)

In [5]:
log_returns = []

for i in range(1,len(prices)):
    x = np.log(prices.squeeze().iloc[i]) - np.log(prices.squeeze().iloc[i-1])
    log_returns.append(x)

log_returns.insert(0,0)

In [6]:
X = pd.DataFrame({
    'Close Prices': prices.squeeze(),
    # 'Log Returns': log_returns,
    # 'Scaled Prices': scaled_prices
})

X['PCT'] = X['Close Prices'].pct_change() * 100
X['PCT-1'] = X['PCT'].shift(1)
X['PCT-2'] = X['PCT'].shift(2)
X['PCT-3'] = X['PCT'].shift(3)
X['PCT-4'] = X['PCT'].shift(4)
X['PCT-5'] = X['PCT'].shift(5)
X['PCT-6'] = X['PCT'].shift(6)
X['PCT-7'] = X['PCT'].shift(7)

X['Volatility'] = X['PCT'].rolling(window=5).std().shift(1)

X = X.dropna()
X

Close Prices       PCT     PCT-1     PCT-2     PCT-3     PCT-4  \
Date                                                                         
2018-01-12   2786.239990  0.674960  0.703365 -0.111223  0.130293  0.166234   
2018-01-16   2776.419922 -0.352449  0.674960  0.703365 -0.111223  0.130293   
2018-01-17   2802.560059  0.941505 -0.352449  0.674960  0.703365 -0.111223   
2018-01-18   2798.030029 -0.161639  0.941505 -0.352449  0.674960  0.703365   
2018-01-19   2810.300049  0.438524 -0.161639  0.941505 -0.352449  0.674960   
...                  ...       ...       ...       ...       ...       ...   
2022-12-23   3844.820068  0.586810 -1.445170  1.486799  0.103734 -0.900752   
2022-12-27   3829.250000 -0.404962  0.586810 -1.445170  1.486799  0.103734   
2022-12-28   3783.219971 -1.202064 -0.404962  0.586810 -1.445170  1.486799   
2022-12-29   3849.280029  1.746133 -1.202064 -0.404962  0.586810 -1.445170   
2022-12-30   3839.500000 -0.254074  1.746133 -1.202064 -0.404962  0.586810   

               PCT-5     PCT-6     PCT-7  Volatility  
Date                                                  
2018-01-12  0.703377  0.402864  0.639882    0.367260  
2018-01-16  0.166234  0.703377  0.402864    0.359961  
2018-01-17  0.130293  0.166234  0.703377    0.470499  
2018-01-18 -0.111223  0.130293  0.166234    0.566624  
2018-01-19  0.703365 -0.111223  0.130293    0.577696  
...              ...       ...       ...         ...  
2022-12-23 -1.113775 -2.492168 -0.605272    1.189847  
2022-12-27 -0.900752 -1.113775 -2.492168    1.168318  
2022-12-28  0.103734 -0.900752 -1.113775    1.095077  
2022-12-29  1.486799  0.103734 -0.900752    1.230941  
2022-12-30 -1.445170  1.486799  0.103734    1.321678  

[1251 rows x 10 columns]

In [7]:
sma_windows = [20, 50, 100, 200]

# Compute multiple SMAs
for window in sma_windows:
    X[f"SMA_{window}"] = X['PCT'].rolling(window=window).mean().shift(1)

X = X.dropna()
X

Close Prices       PCT     PCT-1     PCT-2     PCT-3     PCT-4  \
Date                                                                         
2018-10-29   2641.250000 -0.655960 -1.732726  1.862504 -3.086443 -0.551183   
2018-10-30   2682.629883  1.566678 -0.655960 -1.732726  1.862504 -3.086443   
2018-10-31   2711.739990  1.085133  1.566678 -0.655960 -1.732726  1.862504   
2018-11-01   2740.370117  1.055784  1.085133  1.566678 -0.655960 -1.732726   
2018-11-02   2723.060059 -0.631669  1.055784  1.085133  1.566678 -0.655960   
...                  ...       ...       ...       ...       ...       ...   
2022-12-23   3844.820068  0.586810 -1.445170  1.486799  0.103734 -0.900752   
2022-12-27   3829.250000 -0.404962  0.586810 -1.445170  1.486799  0.103734   
2022-12-28   3783.219971 -1.202064 -0.404962  0.586810 -1.445170  1.486799   
2022-12-29   3849.280029  1.746133 -1.202064 -0.404962  0.586810 -1.445170   
2022-12-30   3839.500000 -0.254074  1.746133 -1.202064 -0.404962  0.586810   

               PCT-5     PCT-6     PCT-7  Volatility    SMA_20    SMA_50  \
Date                                                                       
2018-10-29 -0.429953 -0.036117 -1.439192    1.829262 -0.447894 -0.127809   
2018-10-30 -0.551183 -0.429953 -0.036117    1.820990 -0.498897 -0.147574   
2018-10-31 -3.086443 -0.551183 -0.429953    2.123969 -0.418580 -0.121097   
2018-11-01  1.862504 -3.086443 -0.551183    1.551602 -0.367881 -0.103531   
2018-11-02 -1.732726  1.862504 -3.086443    1.399231 -0.274244 -0.081619   
...              ...       ...       ...         ...       ...       ...   
2022-12-23 -1.113775 -2.492168 -0.605272    1.189847 -0.252571  0.144986   
2022-12-27 -0.900752 -1.113775 -2.492168    1.168318 -0.221815  0.104791   
2022-12-28  0.103734 -0.900752 -1.113775    1.095077 -0.164842  0.144017   
2022-12-29  1.486799  0.103734 -0.900752    1.230941 -0.216986  0.067015   
2022-12-30 -1.445170  1.486799  0.103734    1.321678 -0.284419  0.079083   

             SMA_100   SMA_200  
Date                            
2018-10-29 -0.038871 -0.015387  
2018-10-30 -0.044716 -0.022041  
2018-10-31 -0.032176 -0.012446  
2018-11-01 -0.022393 -0.011727  
2018-11-02 -0.013579 -0.005640  
...              ...       ...  
2022-12-23 -0.056356 -0.044054  
2022-12-27 -0.066126 -0.038974  
2022-12-28 -0.069398 -0.034518  
2022-12-29 -0.079793 -0.036818  
2022-12-30 -0.061094 -0.038791  

[1051 rows x 14 columns]

In [8]:
Data = pd.DataFrame()

Data['PCT today'] = X['PCT']
Data['PCT today-1'] = X['PCT-1']
Data['PCT today-2'] = X['PCT-2']
Data['PCT today-3'] = X['PCT-3']
Data['PCT today-4'] = X['PCT-4']
Data['PCT today-5'] = X['PCT-5']
Data['PCT today-6'] = X['PCT-6']
Data['PCT today-7'] = X['PCT-7']
Data['Volatility'] = X['Volatility']
Data['SMA_20'] = X['SMA_20']
Data['SMA_50'] = X['SMA_50']
Data['SMA_100'] = X['SMA_100']
Data['SMA_200'] = X['SMA_200']

Data = Data.dropna()

Data

PCT today  PCT today-1  PCT today-2  PCT today-3  PCT today-4  \
Date                                                                        
2018-10-29  -0.655960    -1.732726     1.862504    -3.086443    -0.551183   
2018-10-30   1.566678    -0.655960    -1.732726     1.862504    -3.086443   
2018-10-31   1.085133     1.566678    -0.655960    -1.732726     1.862504   
2018-11-01   1.055784     1.085133     1.566678    -0.655960    -1.732726   
2018-11-02  -0.631669     1.055784     1.085133     1.566678    -0.655960   
...               ...          ...          ...          ...          ...   
2022-12-23   0.586810    -1.445170     1.486799     0.103734    -0.900752   
2022-12-27  -0.404962     0.586810    -1.445170     1.486799     0.103734   
2022-12-28  -1.202064    -0.404962     0.586810    -1.445170     1.486799   
2022-12-29   1.746133    -1.202064    -0.404962     0.586810    -1.445170   
2022-12-30  -0.254074     1.746133    -1.202064    -0.404962     0.586810   

            PCT today-5  PCT today-6  PCT today-7  Volatility    SMA_20  \
Date                                                                      
2018-10-29    -0.429953    -0.036117    -1.439192    1.829262 -0.447894   
2018-10-30    -0.551183    -0.429953    -0.036117    1.820990 -0.498897   
2018-10-31    -3.086443    -0.551183    -0.429953    2.123969 -0.418580   
2018-11-01     1.862504    -3.086443    -0.551183    1.551602 -0.367881   
2018-11-02    -1.732726     1.862504    -3.086443    1.399231 -0.274244   
...                 ...          ...          ...         ...       ...   
2022-12-23    -1.113775    -2.492168    -0.605272    1.189847 -0.252571   
2022-12-27    -0.900752    -1.113775    -2.492168    1.168318 -0.221815   
2022-12-28     0.103734    -0.900752    -1.113775    1.095077 -0.164842   
2022-12-29     1.486799     0.103734    -0.900752    1.230941 -0.216986   
2022-12-30    -1.445170     1.486799     0.103734    1.321678 -0.284419   

              SMA_50   SMA_100   SMA_200  
Date                                      
2018-10-29 -0.127809 -0.038871 -0.015387  
2018-10-30 -0.147574 -0.044716 -0.022041  
2018-10-31 -0.121097 -0.032176 -0.012446  
2018-11-01 -0.103531 -0.022393 -0.011727  
2018-11-02 -0.081619 -0.013579 -0.005640  
...              ...       ...       ...  
2022-12-23  0.144986 -0.056356 -0.044054  
2022-12-27  0.104791 -0.066126 -0.038974  
2022-12-28  0.144017 -0.069398 -0.034518  
2022-12-29  0.067015 -0.079793 -0.036818  
2022-12-30  0.079083 -0.061094 -0.038791  

[1051 rows x 13 columns]

In [9]:
InputData = Data.drop('PCT today',axis='columns')
InputData

PCT today-1  PCT today-2  PCT today-3  PCT today-4  PCT today-5  \
Date                                                                          
2018-10-29    -1.732726     1.862504    -3.086443    -0.551183    -0.429953   
2018-10-30    -0.655960    -1.732726     1.862504    -3.086443    -0.551183   
2018-10-31     1.566678    -0.655960    -1.732726     1.862504    -3.086443   
2018-11-01     1.085133     1.566678    -0.655960    -1.732726     1.862504   
2018-11-02     1.055784     1.085133     1.566678    -0.655960    -1.732726   
...                 ...          ...          ...          ...          ...   
2022-12-23    -1.445170     1.486799     0.103734    -0.900752    -1.113775   
2022-12-27     0.586810    -1.445170     1.486799     0.103734    -0.900752   
2022-12-28    -0.404962     0.586810    -1.445170     1.486799     0.103734   
2022-12-29    -1.202064    -0.404962     0.586810    -1.445170     1.486799   
2022-12-30     1.746133    -1.202064    -0.404962     0.586810    -1.445170   

            PCT today-6  PCT today-7  Volatility    SMA_20    SMA_50  \
Date                                                                   
2018-10-29    -0.036117    -1.439192    1.829262 -0.447894 -0.127809   
2018-10-30    -0.429953    -0.036117    1.820990 -0.498897 -0.147574   
2018-10-31    -0.551183    -0.429953    2.123969 -0.418580 -0.121097   
2018-11-01    -3.086443    -0.551183    1.551602 -0.367881 -0.103531   
2018-11-02     1.862504    -3.086443    1.399231 -0.274244 -0.081619   
...                 ...          ...         ...       ...       ...   
2022-12-23    -2.492168    -0.605272    1.189847 -0.252571  0.144986   
2022-12-27    -1.113775    -2.492168    1.168318 -0.221815  0.104791   
2022-12-28    -0.900752    -1.113775    1.095077 -0.164842  0.144017   
2022-12-29     0.103734    -0.900752    1.230941 -0.216986  0.067015   
2022-12-30     1.486799     0.103734    1.321678 -0.284419  0.079083   

             SMA_100   SMA_200  
Date                            
2018-10-29 -0.038871 -0.015387  
2018-10-30 -0.044716 -0.022041  
2018-10-31 -0.032176 -0.012446  
2018-11-01 -0.022393 -0.011727  
2018-11-02 -0.013579 -0.005640  
...              ...       ...  
2022-12-23 -0.056356 -0.044054  
2022-12-27 -0.066126 -0.038974  
2022-12-28 -0.069398 -0.034518  
2022-12-29 -0.079793 -0.036818  
2022-12-30 -0.061094 -0.038791  

[1051 rows x 12 columns]

In [10]:
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - x ** 2

In [11]:
# MLP

np.random.seed(42)

# Initialize neural network parameters
ninputs = 12
nhidden_1 = 5
nhidden_2 = 3
noutput = 1

weights1 = np.random.uniform(-1, 1, (ninputs, nhidden_1))  # Weights from input to hidden
weights2 = np.random.uniform(-1, 1, (nhidden_1, nhidden_2)) # Weights from first hidden to next hidden
weights3 = np.random.uniform(-1, 1, (nhidden_2, noutput)) # Weights to output

hiddenbias_1 = np.random.uniform(-1, 1, (noutput, nhidden_1)) # Bias for first hidden layer
hiddenbias_2 = np.random.uniform(-1, 1, (noutput, nhidden_2)) # Bias for next hidden layer
outbias = np.random.uniform(-1, 1, (noutput, noutput)) # Bias for output layer

learning_rate = 0.005
epochs = 101

k = 0.0002
T = 253

arr = np.arange(1,101)
SRarr = []

dropout_rate = 0.2

for epoch in range(1,epochs):
    
    allocations = np.zeros(len(InputData))
    net_input = np.zeros(len(InputData))
    
    for i in range(1,len(InputData) + 1):
        current_input = InputData.iloc[i-1]
        current_input = current_input.to_numpy().reshape(1, -1)
    
        # Forward Pass
        hidden_input_1 = np.dot(current_input, weights1) + hiddenbias_1
        hidden_output_1 = tanh(hidden_input_1)

        dropout_mask_1 = (np.random.rand(*hidden_output_1.shape) > dropout_rate).astype(float)
        hidden_output_1 = hidden_output_1 * dropout_mask_1

        hidden_input_2 = np.dot(hidden_output_1, weights2) + hiddenbias_2
        hidden_output_2 = tanh(hidden_input_2)

        dropout_mask_2 = (np.random.rand(*hidden_output_2.shape) > dropout_rate).astype(float)
        hidden_output_2 = hidden_output_2 * dropout_mask_2
    
        output_input = np.dot(hidden_output_2, weights3) + outbias
        output = tanh(output_input)
        net_input[i-1] = output_input.item()
        allocations[i-1] = output.item()
    
    # Calculation for Asset Returns and Mu
    asset_returns = allocations * Data['PCT today'].values
    average_daily_return = np.mean(asset_returns)
    average_daily_excess_return = average_daily_return - k
    
    # Calculation of Standard deviation
    squared_deviations = np.square(asset_returns - average_daily_excess_return)
    sigma = np.sqrt(np.mean(squared_deviations))
    
    # Annulaized Sharpe Ratio
    annualized_SR = np.sqrt(T) * (average_daily_excess_return / sigma)
    SRarr.append(annualized_SR)

    # Select random pattern
    num = np.random.randint(0, len(InputData))
    
    # Update weights per pattern    
    # Backpropagation
    a = np.sqrt(T) / sigma
    b = average_daily_excess_return / sigma
    c = (asset_returns[num] - (average_daily_excess_return + k)) / sigma
            
    Ct = a * (1 - (b * c))
    
    beta_output = Ct * Data['PCT today'].iloc[num] * (1 - np.square(allocations[num])) * net_input[num] # Also the delta
    beta_hidden_2 = tanh_derivative(hidden_output_2) * (weights3 * beta_output).T
    beta_hidden_1 = tanh_derivative(hidden_output_1) * np.dot(beta_hidden_2, weights2.T)

    
    weights3 += learning_rate * beta_output
    weights2 += learning_rate * np.dot(hidden_output_1.T, beta_hidden_2)
    weights1 += learning_rate * np.dot(current_input.T, beta_hidden_1)
    outbias += learning_rate * beta_output
    hiddenbias_2 += learning_rate * beta_hidden_2
    hiddenbias_1 += learning_rate * beta_hidden_1
        
    if epoch % 50 == 0:
        print(f"Epoch {epoch}")
        print(f"Gradient: {beta_output}, Weight Update: {learning_rate * beta_output}, Ct: {Ct}")
        print(f"Weights1: {weights1}")
        print(f"Weights2: {weights2}")
        print(f"Weights3: {weights3}")
        print(f"Hiiden Bias1: {hiddenbias_1}, Hiiden Bias2: {hiddenbias_2}, Out Bias: {outbias}")
        print(f"Allocations: {allocations}, Net_Input: {net_input}")
        print(f"Asset Returns: {asset_returns}, Average Daily Excess Return: {average_daily_excess_return}")
        print(f"Sigma: {sigma}, Annualized SR: {annualized_SR}")

Epoch 50
Gradient: -12.155948157117006, Weight Update: -0.06077974078558503, Ct: 13.555534781699802
Weights1: [[-0.64047387  0.66608581  0.69252093  0.25471489 -0.83900605]
 [-0.41983617 -0.72181932  0.57502677  0.16271645  0.52012561]
 [-0.86848584  0.99440027  0.61188403 -0.58863347 -0.60132018]
 [-0.76410559 -0.47060546  0.1263143  -0.11682066 -0.46830175]
 [ 0.54611642 -0.52623312 -0.60485383 -0.31478114  0.0371495 ]
 [ 0.23865397 -0.80104239  0.22306044  0.23370238 -1.03570972]
 [ 0.19194717 -0.67293294 -0.85632018  0.90118096  0.92229092]
 [ 0.32193455 -0.56890744 -0.63167522  0.41191152 -0.23402229]
 [-0.69247102  0.02868762 -0.96844755  0.80929155 -0.45783735]
 [ 0.30740158 -0.38723657  0.05048635  0.09602012 -0.63713187]
 [ 0.95279912  0.55849991  0.87100189  0.78764644  0.20108472]
 [ 0.85240264 -0.81778672 -0.61311127 -0.91082055 -0.34598382]]
Weights2: [[-0.1319176  -0.35654308  0.57220669]
 [-0.34995641 -0.51462719  0.09405206]
 [-0.58557252  0.78728013 -0.93863469]
 [ 1.2

In [12]:
plt.figure(figsize=(12, 6))
plt.plot(arr, SRarr)
plt.xlabel("Epochs")
plt.ylabel("Annualized Sharpe Ratio")
plt.title("ASR per epoch")
plt.show()

In [12]:
test = yf.download('^GSPC', start='2023-01-01', end='2024-12-31', progress=False)
test_prices = test['Close']

In [13]:
test_scaled_prices = []

for i in range(len(test_prices)):
    x = test_prices.squeeze().iloc[i]
    y = (x - test_prices.squeeze().min()) / (test_prices.squeeze().max() - test_prices.squeeze().min())
    test_scaled_prices.append(y)

In [14]:
test_log_returns = []

for i in range(1,len(test_prices)):
    x = np.log(test_prices.squeeze().iloc[i]) - np.log(test_prices.squeeze().iloc[i-1])
    test_log_returns.append(x)

test_log_returns.insert(0,0)

In [15]:
test_X = pd.DataFrame({
    'Close Prices': test_prices.squeeze(),
    # 'Log Returns': test_log_returns,
    # 'Scaled Prices': test_scaled_prices
})

test_X['PCT'] = test_X['Close Prices'].pct_change() * 100
test_X['PCT-1'] = test_X['PCT'].shift(1)
test_X['PCT-2'] = test_X['PCT'].shift(2)
test_X['PCT-3'] = test_X['PCT'].shift(3)
test_X['PCT-4'] = test_X['PCT'].shift(4)
test_X['PCT-5'] = test_X['PCT'].shift(5)
test_X['PCT-6'] = test_X['PCT'].shift(6)
test_X['PCT-7'] = test_X['PCT'].shift(7)

test_X['Volatility'] = test_X['PCT'].rolling(window=5).std().shift(1)

test_X = test_X.dropna()
test_X

Close Prices       PCT     PCT-1     PCT-2     PCT-3     PCT-4  \
Date                                                                         
2023-01-13   3999.090088  0.399686  0.341591  1.284942  0.697823 -0.076763   
2023-01-17   3990.969971 -0.203049  0.399686  0.341591  1.284942  0.697823   
2023-01-18   3928.860107 -1.556260 -0.203049  0.399686  0.341591  1.284942   
2023-01-19   3898.850098 -0.763835 -1.556260 -0.203049  0.399686  0.341591   
2023-01-20   3972.610107  1.891840 -0.763835 -1.556260 -0.203049  0.399686   
...                  ...       ...       ...       ...       ...       ...   
2024-12-23   5974.069824  0.728727  1.086912 -0.086511 -2.949285 -0.386399   
2024-12-24   6040.040039  1.104276  0.728727  1.086912 -0.086511 -2.949285   
2024-12-26   6037.589844 -0.040566  1.104276  0.728727  1.086912 -0.086511   
2024-12-27   5970.839844 -1.105574 -0.040566  1.104276  0.728727  1.086912   
2024-12-30   5906.939941 -1.070200 -1.105574 -0.040566  1.104276  0.728727   

               PCT-5     PCT-6     PCT-7  Volatility  
Date                                                  
2023-01-13  2.284078 -1.164553  0.753897    0.917935  
2023-01-17 -0.076763  2.284078 -1.164553    0.504664  
2023-01-18  0.697823 -0.076763  2.284078    0.544200  
2023-01-19  1.284942  0.697823 -0.076763    1.045997  
2023-01-20  0.341591  1.284942  0.697823    0.819762  
...              ...       ...       ...         ...  
2024-12-23  0.379935 -0.002647 -0.541402    1.534285  
2024-12-24 -0.386399  0.379935 -0.002647    1.585188  
2024-12-26 -2.949285 -0.386399  0.379935    1.705500  
2024-12-27 -0.086511 -2.949285 -0.386399    0.587577  
2024-12-30  1.086912 -0.086511 -2.949285    0.938953  

[493 rows x 10 columns]

In [16]:
sma_windows = [20, 50, 100, 200]

# Compute multiple SMAs
for window in sma_windows:
    test_X[f"SMA_{window}"] = test_X['PCT'].rolling(window=window).mean().shift(1)

test_X = test_X.dropna()
test_X

Close Prices       PCT     PCT-1     PCT-2     PCT-3     PCT-4  \
Date                                                                         
2023-10-31   4193.799805  0.647496  1.201002 -0.480028 -1.183252 -1.433963   
2023-11-01   4237.859863  1.050600  0.647496  1.201002 -0.480028 -1.183252   
2023-11-02   4317.779785  1.885856  1.050600  0.647496  1.201002 -0.480028   
2023-11-03   4358.339844  0.939373  1.885856  1.050600  0.647496  1.201002   
2023-11-06   4365.979980  0.175299  0.939373  1.885856  1.050600  0.647496   
...                  ...       ...       ...       ...       ...       ...   
2024-12-23   5974.069824  0.728727  1.086912 -0.086511 -2.949285 -0.386399   
2024-12-24   6040.040039  1.104276  0.728727  1.086912 -0.086511 -2.949285   
2024-12-26   6037.589844 -0.040566  1.104276  0.728727  1.086912 -0.086511   
2024-12-27   5970.839844 -1.105574 -0.040566  1.104276  0.728727  1.086912   
2024-12-30   5906.939941 -1.070200 -1.105574 -0.040566  1.104276  0.728727   

               PCT-5     PCT-6     PCT-7  Volatility    SMA_20    SMA_50  \
Date                                                                       
2023-10-31  0.726579 -0.168557 -1.258528    1.160115 -0.139690 -0.091748   
2023-11-01 -1.433963  0.726579 -0.168557    1.144175 -0.038594 -0.092557   
2023-11-02 -1.183252 -1.433963  0.726579    1.035674 -0.026613 -0.065990   
2023-11-03 -0.480028 -1.183252 -1.433963    0.872614  0.074200 -0.050363   
2023-11-06  1.201002 -0.480028 -1.183252    0.461169  0.062094 -0.004659   
...              ...       ...       ...         ...       ...       ...   
2024-12-23  0.379935 -0.002647 -0.541402    1.534285 -0.011711  0.054649   
2024-12-24 -0.386399  0.379935 -0.002647    1.585188  0.007385  0.057120   
2024-12-26 -2.949285 -0.386399  0.379935    1.705500  0.047497  0.063790   
2024-12-27 -0.086511 -2.949285 -0.386399    0.587577  0.016858  0.078198   
2024-12-30  1.086912 -0.086511 -2.949285    0.938953 -0.019414  0.046728   

             SMA_100   SMA_200  
Date                            
2023-10-31 -0.021219  0.026037  
2023-11-01 -0.020932  0.027276  
2023-11-02 -0.011575  0.033545  
2023-11-03 -0.002037  0.050755  
2023-11-06  0.000424  0.059271  
...              ...       ...  
2024-12-23  0.075479  0.073168  
2024-12-24  0.096460  0.080076  
2024-12-26  0.125884  0.086158  
2024-12-27  0.155448  0.080354  
2024-12-30  0.134038  0.075789  

[293 rows x 14 columns]

In [17]:
test_Data = pd.DataFrame()

test_Data['Close Prices'] = test_X['Close Prices']
test_Data['PCT today'] = test_X['PCT']
test_Data['PCT today-1'] = test_X['PCT-1']
test_Data['PCT today-2'] = test_X['PCT-2']
test_Data['PCT today-3'] = test_X['PCT-3']
test_Data['PCT today-4'] = test_X['PCT-4']
test_Data['PCT today-5'] = test_X['PCT-5']
test_Data['PCT today-6'] = test_X['PCT-6']
test_Data['PCT today-7'] = test_X['PCT-7']
test_Data['Volatility'] = test_X['Volatility']
test_Data['SMA_20'] = test_X['SMA_20']
test_Data['SMA_50'] = test_X['SMA_50']
test_Data['SMA_100'] = test_X['SMA_100']
test_Data['SMA_200'] = test_X['SMA_200']

test_Data = test_Data.dropna()

test_Data

Close Prices  PCT today  PCT today-1  PCT today-2  PCT today-3  \
Date                                                                         
2023-10-31   4193.799805   0.647496     1.201002    -0.480028    -1.183252   
2023-11-01   4237.859863   1.050600     0.647496     1.201002    -0.480028   
2023-11-02   4317.779785   1.885856     1.050600     0.647496     1.201002   
2023-11-03   4358.339844   0.939373     1.885856     1.050600     0.647496   
2023-11-06   4365.979980   0.175299     0.939373     1.885856     1.050600   
...                  ...        ...          ...          ...          ...   
2024-12-23   5974.069824   0.728727     1.086912    -0.086511    -2.949285   
2024-12-24   6040.040039   1.104276     0.728727     1.086912    -0.086511   
2024-12-26   6037.589844  -0.040566     1.104276     0.728727     1.086912   
2024-12-27   5970.839844  -1.105574    -0.040566     1.104276     0.728727   
2024-12-30   5906.939941  -1.070200    -1.105574    -0.040566     1.104276   

            PCT today-4  PCT today-5  PCT today-6  PCT today-7  Volatility  \
Date                                                                         
2023-10-31    -1.433963     0.726579    -0.168557    -1.258528    1.160115   
2023-11-01    -1.183252    -1.433963     0.726579    -0.168557    1.144175   
2023-11-02    -0.480028    -1.183252    -1.433963     0.726579    1.035674   
2023-11-03     1.201002    -0.480028    -1.183252    -1.433963    0.872614   
2023-11-06     0.647496     1.201002    -0.480028    -1.183252    0.461169   
...                 ...          ...          ...          ...         ...   
2024-12-23    -0.386399     0.379935    -0.002647    -0.541402    1.534285   
2024-12-24    -2.949285    -0.386399     0.379935    -0.002647    1.585188   
2024-12-26    -0.086511    -2.949285    -0.386399     0.379935    1.705500   
2024-12-27     1.086912    -0.086511    -2.949285    -0.386399    0.587577   
2024-12-30     0.728727     1.086912    -0.086511    -2.949285    0.938953   

              SMA_20    SMA_50   SMA_100   SMA_200  
Date                                                
2023-10-31 -0.139690 -0.091748 -0.021219  0.026037  
2023-11-01 -0.038594 -0.092557 -0.020932  0.027276  
2023-11-02 -0.026613 -0.065990 -0.011575  0.033545  
2023-11-03  0.074200 -0.050363 -0.002037  0.050755  
2023-11-06  0.062094 -0.004659  0.000424  0.059271  
...              ...       ...       ...       ...  
2024-12-23 -0.011711  0.054649  0.075479  0.073168  
2024-12-24  0.007385  0.057120  0.096460  0.080076  
2024-12-26  0.047497  0.063790  0.125884  0.086158  
2024-12-27  0.016858  0.078198  0.155448  0.080354  
2024-12-30 -0.019414  0.046728  0.134038  0.075789  

[293 rows x 14 columns]

In [18]:
input_test_data = test_Data.drop(columns=['Close Prices', 'PCT today'])

In [19]:
# Initialize tracking variables
portfolio_values = []
profits = []
cumulative_returns = []
allocations = []

# Initialize portfolio
initial_shares = 100
initial_cash = 100000  # Start with no cash
portfolio_value = initial_shares * test_Data['Close Prices'].iloc[0] + initial_cash # Initial portfolio value
trading_capital = 0.2 * portfolio_value  # 20% of portfolio value for trading
shares_held = initial_shares
cash = initial_cash

cumulative_returns.append(0)
portfolio_values.append(portfolio_value)
profits.append(0)

buy_and_hold_value = initial_shares * test_Data['Close Prices'].iloc[0] + initial_cash
buy_and_hold_cumulative_returns = []
buy_and_hold_cumulative_returns.append(0)
buy_and_hold_profits = []
buy_and_hold_profits.append(0)
buy_and_hold_portfolio_values = []
buy_and_hold_portfolio_values.append(buy_and_hold_value)

# Trading simulation
for i in range(1,len(input_test_data)):
    current_price = test_Data['Close Prices'].iloc[i]
    current_input = input_test_data.iloc[i]
    current_input = current_input.to_numpy().reshape(1, -1)
    
    # Forward Pass
    hidden_input_1 = np.dot(current_input, weights1) + hiddenbias_1
    hidden_output_1 = tanh(hidden_input_1)

    hidden_input_2 = np.dot(hidden_output_1, weights2) + hiddenbias_2
    hidden_output_2 = tanh(hidden_input_2)
    
    output_input = np.dot(hidden_output_2, weights3) + outbias
    allocation = tanh(output_input)
    allocations.append(allocation)

    # Recalculate trading capital dynamically
    # trading_capital = 0.2 * portfolio_value

    # Trading logic with risk management
    if allocation > 0:  # Buy signal
        # Calculate the number of shares to buy, ensuring cash does not go negative
        max_shares_to_buy = int(cash / current_price) if cash > 0 else 0
        shares_to_buy = min(int((trading_capital * allocation) / current_price), max_shares_to_buy)
        cost = shares_to_buy * current_price
        
        # Update portfolio
        shares_held += shares_to_buy
        cash -= cost
    elif allocation < 0:  # Sell signal
        # Calculate the number of shares to sell
        shares_to_sell = int((trading_capital * abs(allocation)) / current_price)
        shares_to_sell = min(shares_to_sell, shares_held)  # Cannot sell more than held
        revenue = shares_to_sell * current_price
        
        # Update portfolio
        shares_held -= shares_to_sell
        cash += revenue

    # Update portfolio value
    new_portfolio_value = shares_held * current_price + cash
    daily_profit = new_portfolio_value - portfolio_values[i-1]  # Profit on this day
    portfolio_values.append(new_portfolio_value)
    profits.append(daily_profit)

    new_buy_and_hold_portfolio_value = initial_shares * current_price + initial_cash
    buy_and_hold_daily_profit = new_buy_and_hold_portfolio_value - buy_and_hold_portfolio_values[i-1]
    buy_and_hold_portfolio_values.append(new_buy_and_hold_portfolio_value)
    buy_and_hold_profits.append(buy_and_hold_daily_profit)

    # Calculate cumulative return
    cumulative_returns.append((new_portfolio_value / portfolio_values[0]) - 1)
    buy_and_hold_cumulative_returns.append(((initial_shares * current_price + initial_cash) / buy_and_hold_value) - 1)
    
    # Update portfolio value
    portfolio_value = new_portfolio_value

# Final portfolio value
print(f"Final Portfolio Value: {portfolio_value}")
print(f"Shares Held: {shares_held}")
print(f"Cash: {cash}")

# Plot daily profits
plt.figure(figsize=(12, 6))
plt.plot(profits, label="Daily Profit/Loss", color="blue")
plt.axhline(0, color='black', linestyle='--', linewidth=1)  # Zero-profit line
plt.xlabel("Days")
plt.ylabel("Profit/Loss ($)")
plt.title("Daily Profit/Loss Over Time")
plt.legend()
plt.show()

# Plot cumulative returns
plt.figure(figsize=(12, 6))
plt.plot(cumulative_returns, label="Strategy Cumulative Returns", color="red")
plt.plot(buy_and_hold_cumulative_returns, label=" Buy&Hold Cumulative Returns", color="green")
plt.axhline(0, color='black', linestyle='--', linewidth=1)  # Zero return line
plt.ylim(-0.1,0.5)
plt.xlabel("Days")
plt.ylabel("Cumulative Return (%)")
plt.title("Cumulative Returns Over Time")
plt.legend()
plt.show()

# Plot buy and hold
# plt.figure(figsize=(12, 6))
# plt.plot(buy_and_hold_cumulative_returns, label="Cumulative Returns", color="green")
# plt.axhline(0, color='black', linestyle='--', linewidth=1)  # Zero return line
# plt.xlabel("Days")
# plt.ylabel("Cumulative Return (%)")
# plt.title("Buy and Hold Cumulative Returns Over Time")
# plt.legend()
# plt.show()

/var/folders/0f/84czy2195_s4j094wj7xpbb80000gn/T/ipykernel_2734/2564741964.py:51: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  shares_to_buy = min(int((trading_capital * allocation) / current_price), max_shares_to_buy)
/var/folders/0f/84czy2195_s4j094wj7xpbb80000gn/T/ipykernel_2734/2564741964.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  shares_to_sell = int((trading_capital * abs(allocation)) / current_price)


Final Portfolio Value: 728108.39453125
Shares Held: 123
Cash: 1554.78173828125


In [20]:
# Calculation for Asset Returns and Mu
asset_returns = allocations * test_Data['PCT today'].values
average_daily_return = np.mean(asset_returns)
average_daily_excess_return = average_daily_return - k
    
# Calculation of Standard deviation
squared_deviations = np.square(asset_returns - average_daily_excess_return)
sigma = np.sqrt(np.mean(squared_deviations))
    
# Annulaized Sharpe Ratio
annualized_SR = np.sqrt(T) * (average_daily_excess_return / sigma)
print(f"Annualized Sharpe Ratio: {annualized_SR}")

Annualized Sharpe Ratio: 2.388904847963839


In [21]:
# Calculate daily returns
daily_returns = np.diff(portfolio_values) / portfolio_values[:-1]

# Calculate average daily return
average_daily_return = np.mean(daily_returns)

# Calculate standard deviation of daily returns
std_dev_daily_returns = np.std(daily_returns)

# Annualize the average daily return and standard deviation
annualized_return = average_daily_return * 253
annualized_std_dev = std_dev_daily_returns * np.sqrt(253)

# Risk-free rate
risk_free_rate = 0.0002

# Calculate Sharpe Ratio
sharpe_ratio = (annualized_return - risk_free_rate) / annualized_std_dev

print(f"Sharpe Ratio: {sharpe_ratio}")

Sharpe Ratio: 2.4283139928817272


In [22]:
sum(profits)

208728.4140625

In [23]:
sum(allocations)

array([[263.86381458]])

In [24]:
sum(buy_and_hold_profits)

171314.013671875

In [25]:
allocations

[array([[0.99821967]]),
 array([[0.93415947]]),
 array([[0.73308836]]),
 array([[0.72164704]]),
 array([[0.96103915]]),
 array([[0.99774089]]),
 array([[0.99029646]]),
 array([[0.98701907]]),
 array([[0.99572882]]),
 array([[0.98724039]]),
 array([[0.99458473]]),
 array([[0.99831266]]),
 array([[-0.13549628]]),
 array([[0.99842252]]),
 array([[0.99386993]]),
 array([[0.9983043]]),
 array([[0.99720523]]),
 array([[0.99809508]]),
 array([[0.99243533]]),
 array([[0.99819259]]),
 array([[0.99464682]]),
 array([[0.99767241]]),
 array([[0.99827139]]),
 array([[0.97004603]]),
 array([[0.99355137]]),
 array([[0.99314115]]),
 array([[0.9961278]]),
 array([[0.99835922]]),
 array([[0.99151123]]),
 array([[0.99685768]]),
 array([[0.99719554]]),
 array([[0.99760685]]),
 array([[0.99779557]]),
 array([[0.99820915]]),
 array([[0.99677885]]),
 array([[0.99099571]]),
 array([[0.99128344]]),
 array([[0.99456443]]),
 array([[0.99267946]]),
 array([[0.99853406]]),
 array([[0.59411848]]),
 array([[0.957485